In [3]:
import numpy as np

array = np.random.randint(1, 10, size=4).reshape(2,2)
print(array)

[[4 3]
 [1 1]]


In [4]:
result_array = array *10
print(result_array)

[[40 30]
 [10 10]]


In [9]:
array1 = np.arange(4).reshape(2,2)
array2 = np.arange(2)

array3= array1 + array2
print(array1)
print(array2)
print(array3)

[[0 1]
 [2 3]]
[0 1]
[[0 2]
 [2 4]]


In [18]:
array1 = np.arange(0,8).reshape(2,4)
array2 = np.arange(0,8).reshape(2,4)
array3 = np.concatenate([array1,array2],axis=0)
array4 = np.arange(0,4).reshape(4,1) #(4*1)

print(array1)
print(array2)
print(array3)
print(array4)
print(array3+ array4)

[[0 1 2 3]
 [4 5 6 7]]
[[0 1 2 3]
 [4 5 6 7]]
[[0 1 2 3]
 [4 5 6 7]
 [0 1 2 3]
 [4 5 6 7]]
[[0]
 [1]
 [2]
 [3]]
[[ 0  1  2  3]
 [ 5  6  7  8]
 [ 2  3  4  5]
 [ 7  8  9 10]]


In [24]:
# 마스킹 연산
array1 = np.arange(16).reshape(4,4)
print(array1)

array2 = array1 <10
print(array2)

array1[array2] = 100
print(array1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True False False]
 [False False False False]]
[[100 100 100 100]
 [100 100 100 100]
 [100 100  10  11]
 [ 12  13  14  15]]


In [25]:
# 집계함수
array = np.arange(16).reshape(4,4)
print("최대값:", np.max(array))
print("최소값:", np.min(array))
print("합계:", np.sum(array))
print("평균값:", np.mean(array))

최대값: 15
최소값: 0
합계: 120
평균값: 7.5


In [29]:
array = np.arange(16).reshape(4,4)
print(array)
print("행합계:", np.sum(array, axis=0))
print("열합계:", np.sum(array, axis=1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
행합계: [24 28 32 36]
열합계: [ 6 22 38 54]
