In [11]:
import numpy as np

data = np.random.randn(5)  #임의 정보 입력
print(data)

np.save('12345.npy',data) # 파일 저장
data = []
print(data)

data = np.load('12345.npy') #파일 로드
print(data)

[-0.73533358 -0.79566429 -0.95793588  0.42393119  0.08970654]
[]
[-0.73533358 -0.79566429 -0.95793588  0.42393119  0.08970654]


In [24]:
data1 = np.array([1,2,3])
data2 = np.array([10,20,30])
np.savez('datafile2.npz', data1 = data1, data2 = data2) #세이브
data1 = [] # 데이터 삭제
data2 = []
outfile = np.load('datafile2.npz') #로드
print(outfile.files)
data1 = outfile['data1'] #data1 꺼내기
data2 = outfile['data2'] #data2 꺼내기
print(data1)
print(data2)

['data1', 'data2']
[1 2 3]
[10 20 30]
