In [4]:
import numpy as np
x = np.array([1,1,2,3,5,8,13])
x > 3

array([False, False, False, False,  True,  True,  True])

In [6]:
x[x>3]

array([ 5,  8, 13])

In [7]:
x[x>3] = 999
print(x)

[  1   1   2   3 999 999 999]
