In [7]:
import numpy as np
x = np.arange(10)
print(x)
print(x[5:10]) # 5~10까지
print(x[:10])  #처음부터 ~10까지
print(x[5:])   #5부터 끝까지
print(x[3:8:2]) # 3부터 8까지 2간격으로
print(x[::-1])  # 역순


[0 1 2 3 4 5 6 7 8 9]
[5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[5 6 7 8 9]
[3 5 7]
[9 8 7 6 5 4 3 2 1 0]


In [15]:
y = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(y)
print(y[:2, 1:2]) # 2행까지  1번 인덱스 출력

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2]
 [5]]
