In [4]:
import numpy as np
x = np.array([[1,2,3],[4,5,6]])
print(x)

[[1 2 3]
 [4 5 6]]


행렬의 크기는 ndarray변수명.shape 명령으로 알 수 있습니다.

In [6]:
x.shape

(2, 3)

In [14]:
# 이 출력은()로 둘러싸여 있으므로 tuple형으로 나타납니다. 다음과 같이 입력하여 w와 h에 각각 2와 3을 저장할 수 있습니다.
w, h = x.shape
print(w)
print(h)
print(type(x.shape))
print(type(x))

2
3
<class 'tuple'>
<class 'numpy.ndarray'>


In [16]:
# 요소의 참조
x = np.array([[1,2,3],[4,5,6]])
x[1,2] 

6

In [24]:
# 요소의 수정
x = np.array([[1,2,3],[4,5,6]])
x[0,2] = 300
print(x)

[[  1   2 300]
 [  4   5   6]]


In [36]:
print(np.zeros(10))

print(np.zeros((2, 10)))

print(np.ones(10))

print(np.ones((5,10)))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [48]:
print(np.random.rand(2,3))  # 2행 3열
print(np.random.randn(3,4)) # 3행 4열
print(np.random.randint(3, 7, 10)) # 3부터 7까지 길이

[[0.18416384 0.59355989 0.14383062]
 [0.07045159 0.87947735 0.35563035]]
[[ 0.61689258 -1.77575332  0.35401612  0.93112021]
 [-0.14592663  0.14216886 -0.51829656  0.78396991]
 [-1.06567369 -0.29492083  0.6411016  -0.22388893]]
[4 4 6 4 6 5 6 5 6 6]


In [51]:
a= np.arange(15)
print(a)
a.reshape(3,5)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [53]:
x = np.array([[3,3,3],[5,5,5]])
y = np.array([[2,2,2],[2,2,2]])
print(x+y)

[[5 5 5]
 [7 7 7]]


In [59]:
# 스칼라 행렬 곱
x = np.array([[4,4,4],[8,8,8]])
print(2 * x)



[[ 8  8  8]
 [16 16 16]]


In [61]:
# 행렬 곱의 계산
# 변수명A.dot(변수명B)
v = np.array([[1,2,3],[4,5,6]])
w = np.array([[1,1],[2,2],[3,3]])
print(v.dot(w))

[[14 14]
 [32 32]]
